CREATE TABLE IF NOT EXISTS QRadar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  offense_id BIGINT NOT NULL,
  domain_id INT NOT NULL,
  domain_name VARCHAR(150) NULL,
  offense_status VARCHAR(10) NOT NULL,
  offense_note_ids VARCHAR(500) NOT NULL,
  last_updated_time BIGINT NOT NULL,
  
  incident_id INT NULL,
  incident_status VARCHAR(10) NULL,
  incident_note_ids VARCHAR(500) NULL,
  org_name VARCHAR(150) NULL,
  org_id INT NULL,
  description VARCHAR(500) NOT NULL,
  
  PRIMARY KEY(id)
);
